(function () {

    var HomeView = function (data) {
        return (
                '<div id="homeFrame">'
                    + '<div class="jumbotron">'
                        + '<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">'
                            + '<!-- Indicators -->'
                            + '<ol class="carousel-indicators">'
                                + '<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>'
                                + '<li data-target="#carousel-example-generic" data-slide-to="1"></li>'
                                + '<li data-target="#carousel-example-generic" data-slide-to="2"></li>'
                            + '</ol>'
                            + '<!-- Wrapper for slides -->'
                            + '<div class="carousel-inner" role="listbox">'
                                + '<div class="item active">'
                                    + '<img src="./music' + data.Do[0].url + '" class="carousel-inner-img" alt="">'
                                    + '<div class="carousel-caption">'
                                        + '<h3>Taylor Swift<h3>'
                                    + '</div>'
                                + '</div>'
                                + '<div class="item">'
                                    + '<img src="./music' + data.Do[1].url + '" class="carousel-inner-img" alt="">'
                                    + '<div class="carousel-caption">'
                                        + '<h3>Jay Chou</h3>'
                                    + '</div>'
                                + '</div>'
                                + '<div class="item">'
                                    + '<img src="./music' + data.Do[2].url + '" class="carousel-inner-img" alt="">'
                                    + '<div class="carousel-caption">'
                                        + '<h3>Wuclef Jean</h3>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                            + '<!-- Controls -->'
                            + '<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">'
                                + '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>'
                                + '<span class="sr-only">Previous</span>'
                            + '</a>'
                            + '<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">'
                                + '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>'
                                + '<span class="sr-only">Next</span>'
                            + '</a>'
                        + '</div>'
                    + '</div>'
                    + '<div class="jumbotron">'
                        + '<h1>Do you like it ?</h1>'
                        + '<p>Countryside music -- Cordial and warm without losing the popular elements</p>'
                        + '<p><button type="button" class="btn btn-sm song-play home-music-listen" name="countryside"><span class="glyphicon glyphicon-headphones"></span>&nbsp;&nbsp;Play it now*</button></p>'
                    + '</div>'
                    + '<div class="jumbotron">'
                        + '<div class="row">'
                            + '<div class="col-sm-6">'
                                + '<h1>Or this ?</h1>'
                                + '<p>Light music -- Simple structure, Lively rhythm, beautiful melody</p>'
                                + '<p><button type="button" class="btn btn-sm song-play home-music-listen" name="light"><span class="glyphicon glyphicon-headphones"></span>&nbsp;&nbsp;Play it now*</button></p>'
                            + '</div>'
                            + '<div class="col-sm-6">'
                                + '<div class="thumbnail">'
                                    + '<img src="./music' + data.Or[0].url + '" alt="">'
                                + '</div>'
                            + '</div>'
                        + '</div>'
                    + '</div>'
                    + '<div class="jumbotron">'
                        + '<h1>Whatever you like</h1>'
                        + '<p>Here, you can find what you want</p>'
                        + '<p><button type="button" class="btn btn-sm song-play home-music-listen" name="other"><span class="glyphicon glyphicon-headphones"></span>&nbsp;&nbsp;Play it now*</button></p>'
                        + '<div class="what-ever">'
                            + '<div class="row">'
                                + '<div class="col-sm-6 col-md-6">'
                                    + '<div class="thumbnail">'
                                        + '<img src="./music' + data.Whatever[0].url + '" alt="">'
                                        + '<div class="caption">'
                                            + '<h3>Popular music</h3>'
                                            + '<p>Cras justo odio, dapibus .&nbsp;&nbsp;<a href="javascript:;" class="song-play" name="popular"></a></p>'
                                            + '<p><span class="what-ever-listen song-play" name="popular">Play it now ></span></p>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                                + '<div class="col-sm-6 col-md-6">'
                                    + '<div class="thumbnail">'
                                        + '<img src="./music' + data.Whatever[1].url + '" alt="">'
                                        + '<div class="caption">'
                                            + '<h3>Jazz music</h3>'
                                            + '<p>Cras justo odio, dapibus .&nbsp;&nbsp;<a href="javascript:;" class="song-play" name="jazz"></a></p>'
                                            + '<p><span class="what-ever-listen song-play" name="jazz">Play it now ></span></p>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                            + '<div class="row">'
                                + '<div class="col-sm-6 col-md-6">'
                                    + '<div class="thumbnail">'
                                        + '<img src="./music' + data.Whatever[2].url + '" alt="">'
                                        + '<div class="caption">'
                                            + '<h3>British music</h3>'
                                            + '<p>Cras justo odio, dapibus.&nbsp;&nbsp;<a href="javascript:;" class="song-play" name="british"></a></p>'
                                            + '<p><span class="what-ever-listen song-play" name="british">Play it now ></span></p>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                                + '<div class="col-sm-6 col-md-6">'
                                    + '<div class="thumbnail">'
                                        + '<img src="./music' + data.Whatever[3].url + '" alt="">'
                                        + '<div class="caption">'
                                            + '<h3>Rock music</h3>'
                                            + '<p>Cras justo odio, dapibus.&nbsp;&nbsp;<a href="javascript:;" class="song-play" name="rock"></a></p>'
                                            + '<p><span class="what-ever-listen song-play" name="rock">Play it now ></span></p>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                            + '<div class="row">'
                                + '<div class="col-sm-6 col-md-6">'
                                    + '<div class="thumbnail">'
                                        + '<img src="./music' + data.Whatever[4].url + '" alt="">'
                                        + '<div class="caption">'
                                           + ' <h3>Classical music</h3>'
                                            + '<p>Cras justo odio, dapibus.&nbsp;&nbsp;<a href="javascript:;" class="song-play" name="classical"></a></p>'
                                            + '<p><span class="what-ever-listen song-play" name="classical">Play it now ></span></p>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                                + '<div class="col-sm-6 col-md-6">'
                                    + '<div class="thumbnail">'
                                        + '<img src="./music' + data.Whatever[5].url + '" alt="">'
                                        + '<div class="caption">'
                                            + '<h3>Electronic music</h3>'
                                            + '<p>Cras justo odio, dapibus.&nbsp;&nbsp;<a href="javascript:;" class="song-play" name="electronic"></a></p>'
                                            + '<p><span class="what-ever-listen song-play" name="electronic">Play it now ></span></p>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                        + '</div>'
                    + '</div>'
                    + '<div class="jumbotron">'
                        + '<h1>Likesw-Music</h1>'
                    + '</div>'
                + '</div>'
            );
    }

    window.HomeView = HomeView;
}());