(function () {

    var LibraryView = function (data) {

        var s_html = '<li class="list-group-item"><div class="alert alert-danger" role="alert">Sorry, Nothing!</div></li>';
        var al_html = '<div class="alert alert-danger" role="alert">Sorry, Nothing!</div>';
        var ar_html = ar_html;
        if (data.songs) {
            s_html = '';
            data.songs.forEach(function (d, i) {
                s_html += '<li class="list-group-item"><img src="./music' + d.image + '" alt=""><span class="rank">' + (i + 1) + '</span>' + d.name + '</li>';
            });
        }

        if (data.albums) {
            al_html = '';
            data.albums.forEach(function (d, i) {
                al_html += '<div class="col-xs-6 col-sm-4 lib-album-item song-play" name="albums-' + d.name + '">'
                                + '<img src="./music' + d.image + '" alt="...">'
                                + '<div class="caption">'
                                    + '<p class="lib-album-name">' + d.name + '</p>'
                                    + '<p class="lib-album-info">' + d.tags + '</p>'
                                + '</div>'
                                + '<div class="lib-album-item-play">'
                                    + '<span class="glyphicon glyphicon-headphones"></span>'
                                + '</div>'
                            + '</div>'
            });
        }

        return (
            '<div id="libraryFrame">'
                + '<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">'
                    + '<div class="panel panel-default">'
                        + '<div class="panel-heading" role="tab" id="headingOne">'
                            + '<div class="row lib-category-header">'
                                + '<div class="col-xs-4 lib-category-title">Song</div>'
                                + '<div class="col-xs-8 lib-category-option">'
                                    + '<span class="option-item" name="song">See More</span>'
                                + '</div>'
                            + '</div>'
                            + '<div class="row lib-category-container">'
                                + '<div class="col-sm-5 lib-theme">'
                                    + '<a href="javascript:;" class="thumbnail">'
                                        + '<img src="./images/q.jpg" alt="">'
                                        + '<div class="lib-play song-play" name="hot-songs">'
                                            + '<div>'
                                                + '<h2>TOP SONGS</h2>'
                                                + '<p>Play ></p>'
                                            + '</div>'
                                        + '</div>'
                                    + '</a>'
                                + '</div>'
                                + '<div class="col-sm-7 lib-content">'
                                    + '<div class="lib-content-item">'
                                        + '<div class="lib-theme-option">'
                                            + '<span class="glyphicon glyphicon-headphones lib-top-play"></span>'
                                            + '<span class="glyphicon glyphicon-menu-right" style="display: none;"></span>'
                                        + '</div>'
                                        + '<div>'
                                            + '<ul class="list-group" id="libSongList">'
                                                + s_html
                                            + '</ul>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                            + '<div class="see-more">'
                                + '<p class="panel-title">'
                                    + '<a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">'
                                        + 'See More&nbsp;&nbsp;'
                                        + '<span class="glyphicon glyphicon-menu-down"></span>'
                                    + '</a>'
                                + '</p>'
                            + '</div>'
                        + '</div>'
                        + '<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">'
                            + '<div class="panel-body">'
                                + 'Anim pariatur cliche reprehenderit,'
                            + '</div>'
                        + '</div>'
                    + '</div>'
                    + '<div class="panel panel-default">'
                        + '<div class="panel-heading" role="tab" id="headingTwo">'
                            + '<div class="row lib-category-header">'
                                + '<div class="col-xs-4 lib-category-title">Album</div>'
                                + '<div class="col-xs-8 lib-category-option">'
                                    + '<span class="option-item" name="album">See More</span>'
                                + '</div>'
                            + '</div>'
                            + '<div class="row lib-category-container">'
                                + '<div class="col-sm-5 lib-theme">'
                                    + '<a href="javascript:;" class="thumbnail">'
                                        + '<img src="./images/q.jpg" alt="">'
                                        + '<div class="lib-play song-play" name="hot-albums">'
                                            + '<div>'
                                                + '<h2>TOP ALBUMS</h2>'
                                                + '<p>Play ></p>'
                                            + '</div>'
                                        + '</div>'
                                    + '</a>'
                                + '</div>'
                                + '<div class="col-sm-7 lib-content">'
                                    + '<div class="lib-content-item">'
                                        + '<div class="lib-theme-option">'
                                            + '<span class="glyphicon glyphicon-menu-right" style="display: none;"></span>'
                                        + '</div>'
                                        + '<div class="row" id="libAlbumList">'
                                            + al_html
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                            + '<div class="see-more">'
                                + '<p class="panel-title">'
                                    + '<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">'
                                        + 'See More&nbsp;&nbsp;'
                                        + '<span class="glyphicon glyphicon-menu-down"></span>'
                                    + '</a>'
                                + '</p>'
                            + '</div>'
                        + '</div>'
                        + '<div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">'
                            + '<div class="panel-body">'
                                + 'Anim pariatur cliche reprehenderit,'
                            + '</div>'
                        + '</div>'
                    + '</div>'
                    + '<div class="panel panel-default">'
                        + '<div class="panel-heading" role="tab" id="headingThree">'
                            + '<div class="row lib-category-header">'
                                + '<div class="col-xs-4 lib-category-title">Artist</div>'
                                + '<div class="col-xs-8 lib-category-option">'
                                    + '<span class="option-item" name="artist">See More</span>'
                                + '</div>'
                            + '</div>'
                            + '<div class="row lib-category-container">'
                                + '<div class="col-sm-5 lib-theme">'
                                    + '<a href="javascript:;" class="thumbnail">'
                                        + '<img src="./images/q.jpg" alt="">'
                                        + '<div class="lib-play song-play" name="hot-artist">'
                                           + ' <div>'
                                                + '<h2>TOP ARTISTS</h2>'
                                                + '<p>Play ></p>'
                                            + '</div>'
                                        + '</div>'
                                    + '</a>'
                                + '</div>'
                                + '<div class="col-sm-7 lib-content">'
                                    + '<div class="lib-content-item">'
                                        + '<div class="lib-theme-option">'
                                            + '<span class="glyphicon glyphicon-menu-right" style="display: none;"></span>'
                                        + '</div>'
                                        + '<div id="libArtistList">'
                                            + '<div class="l-item song-play" id="lItem-0" name="artists-' + data.artists[0].name + '" style="width: 100px; height: 100px; border-radius: 50px;">'
                                                + '<img src="./music' + data.artists[0].image + '" alt="...">'
                                            + '</div>'
                                            + '<div class="l-item song-play" id="lItem-1" name="artists-' + data.artists[1].name + '" style="width: 140px; height: 140px; border-radius: 70px;">'
                                                + '<img src="./music' + data.artists[1].image + '" alt="...">'
                                            + '</div>'
                                            + '<div class="l-item song-play" id="lItem-2" name="artists-' + data.artists[2].name + '" style="width: 80px; height: 80px; border-radius: 40px;">'
                                                + '<img src="./music' + data.artists[2].image + '" alt="...">'
                                            + '</div>'
                                            + '<div class="l-item song-play" id="lItem-3" name="artists-' + data.artists[3].name + '" style="width: 90px; height: 90px; border-radius: 45px;">'
                                                + '<img src="./music' + data.artists[3].image + '" alt="...">'
                                            + '</div>'
                                            + '<div class="l-item song-play" id="lItem-4" name="artists-' + data.artists[4].name + '" style="width: 130px; height: 130px; border-radius: 65px;">'
                                                + '<img src="./music' + data.artists[4].image + '" alt="...">'
                                            + '</div>'
                                            + '<div class="l-item song-play" id="lItem-5" name="artists-' + data.artists[5].name + '" style="width: 100px; height: 100px; border-radius: 50px;">'
                                                + '<img src="./music' + data.artists[5].image + '" alt="...">'
                                            + '</div>'
                                            + '<div class="l-item song-play" id="lItem-6" name="artists-' + data.artists[6].name + '" style="width: 120px; height: 120px; border-radius: 60px;">'
                                                + '<img src="./music' + data.artists[6].image + '" alt="...">'
                                            + '</div>'
                                        + '</div>'
                                    + '</div>'
                                + '</div>'
                            + '</div>'
                            + '<div class="see-more">'
                                + '<p class="panel-title">'
                                    + '<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">'
                                        + 'See More&nbsp;&nbsp;'
                                        + '<span class="glyphicon glyphicon-menu-down"></span>'
                                    + '</a>'
                                + '</p>'
                            + '</div>'
                        + '</div>'
                        + '<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">'
                            + '<div class="panel-body">'
                                + 'Anim pariatur cliche reprehenderit,'
                            + '</div>'
                        + '</div>'
                    + '</div>'
                    + '<div class="panel">'
                    + '</div>'
                + '</div>'
            + '</div>'
        );

    }

    window.LibraryView = LibraryView;
}());