(function () {

    var RegisterModal = function (data) {

        return ('<div class="modal-dialog" role="document">'
                    + '<div class="modal-content">'
                        + '<div class="modal-header">'
                            + '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'
                            + '<h4 class="modal-title" id="myModalLabel">Register</h4>'
                        + '</div>'
                        + '<div class="modal-body">'
                            + '<form method="post" name="registerForm" enctype="multipart/form-data" action="javascript:;" class="form-horizontal" id="registerAccountInfo">'
                                + '<div class="form-group" style="text-align: center;">'
                                    + '<div class="col-sm-4">'
                                        + '<img class="account-photo account-default-photo" id="registerPhoto" alt="Brand" src="./images/logo.png">'
                                    + '</div>'
                                    + '<div class="col-sm-2">'
                                        + '<button type="button" class="btn btn-default register-photo-choose-btn">Choose</button>'
                                        + '<input type="file" name="photo" class="modal-file-input hidden" id="registerPhotoChoose" placeholder="Upload"/>'
                                    + '</div>'
                                + '</div>'
                                + '<div class="form-group">'
                                    + '<label for="inputEmail3" class="col-sm-2 control-label">Email</label>'
                                    + '<div class="col-sm-10">'
                                        + '<input type="email" name="email" class="form-control" id="registerEmail" placeholder="Email">'
                                    + '</div>'
                                + '</div>'
                                + '<div class="form-group">'
                                    + '<label for="inputPassword3" class="col-sm-2 control-label">Password</label>'
                                    + '<div class="col-sm-10">'
                                        + '<input type="password" name="password" class="form-control" id="registerPassword" placeholder="Password">'
                                    + '</div>'
                                + '</div>'
                                + '<div class="form-group">'
                                    + '<label class="col-sm-2 control-label">Name</label>'
                                    + '<div class="col-sm-10">'
                                        + '<input type="text" name="name" class="form-control" id="registerName" placeholder="kyswii">'
                                    + '</div>'
                                + '</div>'
                                + '<div class="form-group">'
                                    + '<label class="col-sm-2 control-label">tags</label>'
                                    + '<div class="col-sm-10">'
                                        + '<input type="text" name="tags" class="form-control" id="registerTags" placeholder="...">'
                                    + '</div>'
                                + '</div>'
                                + '<div class="form-group">'
                                    + '<label class="col-sm-2 control-label">Region</label>'
                                    + '<div class="col-sm-10">'
                                        + '<input type="text" name="region" class="form-control" id="registerRegion" placeholder="England">'
                                    + '</div>'
                                + '</div>'
                            + '</form>'
                        + '</div>'
                        + '<div class="modal-footer">'
                            + '<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>'
                            + '<button type="button" class="btn btn-primary" id="registerSubmit">Submit</button>'
                        + '</div>'
                    + '</div>'
                + '</div>'
        );
    }

    window.RegisterModal = RegisterModal;
}());